apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    upstream backend {
      server hello-service:8080;
    }

    server {
      listen 80;
      location / {
        proxy_pass http://backend;
      }
    }
