---
- name: Manage Ubuntu and RedHat Linux servers
  hosts: all
  become: true
  gather_facts: yes

  vars:
    apache_ubuntu_package: apache2
    mariadb_redhat_package: mariadb-server
    hello_world_content: "<html><body><h1>Hello world</h1></body></html>"

  tasks:
    # update repositories for all systems (update_cache: yes)
    # upgrade servers with the latest packages available for the system version
    # Ubuntu
    - name: Upgrade all packages on Ubuntu
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
    # RedHat
    - name: Upgrade all packages on RedHat
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    # gather facts about systems
    - name: Gather installed packages
      ansible.builtin.package_facts:
        manager: auto

    # make sure that Apache webserver is present on Ubuntu servers only
    - name: Ensure Apache is installed on Ubuntu
      ansible.builtin.package:
        name: "{{ apache_ubuntu_package }}"
        state: present
      when: ansible_os_family == "Debian"

    # if system is Ubuntu and Apache is installed, launch a simple configuration showing html document with “Hello world”
    # once the Apache’s configuration file has been updated - Apache process should be restarted/reloaded to pick up the changes in configuration
    - name: Create simple Apache HTML page (Hello world) on Ubuntu
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "{{ hello_world_content }}"
        owner: www-data
        group: www-data
        mode: '0644'
      when: ansible_os_family == "Debian" and
            "'apache2' in ansible_facts.packages"
      notify: Restart Apache

    # make sure that MariaDB is installed on RedHat servers only

    - name: Ensure MariaDB is installed on RedHat
      ansible.builtin.package:
        name: "{{ mariadb_redhat_package }}"
        state: present
      when: ansible_os_family == "RedHat"

  handlers:
    - name: Restart Apache
      ansible.builtin.service:
        name: "{{ apache_ubuntu_package }}"
        state: restarted
